export type ApiErrorSeverity = "error" | "warning" | "info";

export type ApiErrorCatalogEntry = {
  code: string;
  domain: string;
  severity: ApiErrorSeverity;
  summary: string;
  messages: string[];
  sources: string[];
  debug: string[];
};

export const API_ERROR_CATALOG: ApiErrorCatalogEntry[] = [
  {
    code: "API-001",
    domain: "API",
    severity: "error",
    summary: "Request validation failed.",
    messages: ["API-001: Request validation failed"],
    sources: ["src/middleware/validate.ts"],
    debug: ["Inspect issues.fieldErrors in response", "Validate request body/query/params against zod schema"],
  },
  {
    code: "API-002",
    domain: "API",
    severity: "warning",
    summary: "Rate limit exceeded.",
    messages: ["API-002: Too many requests. Retry later."],
    sources: ["src/middleware/rateLimiter.ts"],
    debug: ["Check client retry/backoff", "Reduce burst traffic", "Inspect per-user and per-ip limiter config"],
  },
  {
    code: "API-003",
    domain: "API",
    severity: "error",
    summary: "AI payload exceeded configured limits.",
    messages: [
      "API-003: acceptance_criteria exceeds configured size limit for AI scoring",
      "API-003: cached_diff exceeds configured size limit for AI scoring",
    ],
    sources: ["src/services/aiScoring.service.ts"],
    debug: ["Trim acceptance criteria length", "Reduce cached diff size before scoring"],
  },
  {
    code: "API-004",
    domain: "API",
    severity: "error",
    summary: "CORS origin rejected.",
    messages: ["API-004: Origin is not allowed by CORS"],
    sources: ["src/app.ts"],
    debug: ["Add frontend origin to CORS_ORIGINS", "Verify protocol/host/port match"],
  },
  {
    code: "API-005",
    domain: "API",
    severity: "error",
    summary: "Unexpected server failure fallback.",
    messages: ["API-005: Unexpected failure"],
    sources: ["src/middleware/globalErrorHandler.ts"],
    debug: ["Inspect server logs with request_id", "Check previous wrapped AppError before fallback"],
  },
  {
    code: "AUTH-001",
    domain: "AUTH",
    severity: "error",
    summary: "Refresh token/session issue.",
    messages: ["AUTH-001: Refresh token missing", "AUTH-001: Token refreshed"],
    sources: ["src/routes/auth.ts"],
    debug: ["Check auth cookies and expiry", "Verify refresh token rotation flow"],
  },
  {
    code: "AUTH-002",
    domain: "AUTH",
    severity: "error",
    summary: "Wallet signature was declined or not approved.",
    messages: ["AUTH-002: Signature verification declined", "AUTH-002: Signature declined. Please approve in your wallet."],
    sources: ["src/routes/auth.ts", "src/hooks/useWallet.ts"],
    debug: ["Prompt wallet signature again", "Confirm wallet popup was approved"],
  },
  {
    code: "AUTH-003",
    domain: "AUTH",
    severity: "error",
    summary: "Session wallet binding mismatch.",
    messages: ["AUTH-003: Session is bound to a different wallet", "AUTH-003: Session wallet binding mismatch"],
    sources: ["src/routes/auth.ts", "src/middleware/auth.ts"],
    debug: ["Logout and login with correct wallet", "Clear stale auth token/cookie"],
  },
  {
    code: "AUTH-004",
    domain: "AUTH",
    severity: "error",
    summary: "Credential/auth state invalid.",
    messages: ["AUTH-004: Invalid email or password", "AUTH-004: Connection lost. Reconnecting..."],
    sources: ["src/routes/auth.ts", "src/hooks/useWallet.ts"],
    debug: ["Verify email/password", "Retry wallet connection handshake"],
  },
  {
    code: "AUTH-005",
    domain: "AUTH",
    severity: "error",
    summary: "Account restricted or signature pending.",
    messages: ["AUTH-005: Account is restricted", "AUTH-005: Wallet connected, but signature verification is still required."],
    sources: ["src/routes/auth.ts", "src/hooks/useWallet.ts"],
    debug: ["Check sanctions/compliance flags", "Complete signature verification"],
  },
  {
    code: "AUTH-006",
    domain: "AUTH",
    severity: "warning",
    summary: "Registration blocked because account already exists.",
    messages: ["AUTH-006: Account already exists for this email"],
    sources: ["src/routes/auth.ts"],
    debug: ["Use login instead", "Use password reset flow if needed"],
  },
  {
    code: "AUTH-007",
    domain: "AUTH",
    severity: "warning",
    summary: "Too many login failures.",
    messages: ["AUTH-007: Too many failed login attempts. Retry later."],
    sources: ["src/routes/auth.ts"],
    debug: ["Wait lockout period", "Check brute-force protection thresholds"],
  },
  {
    code: "AI-C-001",
    domain: "AI",
    severity: "error",
    summary: "Client score flagging rules violated.",
    messages: [
      "AI-C-001: Submission not found",
      "AI-C-001: Only bounty client can flag AI score",
      "AI-C-001: Client flag window expired",
      "AI-C-001: score is not published yet",
      "AI-C-001: score flag window (48h) has expired",
    ],
    sources: ["src/services/aiScoring.service.ts", "src/routes/submissions.ts"],
    debug: ["Verify submission exists", "Verify caller is bounty creator", "Confirm score publish timestamp <48h"],
  },
  {
    code: "AI-C-002",
    domain: "AI",
    severity: "error",
    summary: "Invalid AI scoring input.",
    messages: ["AI-C-002: acceptance_criteria cannot be empty for AI scoring"],
    sources: ["src/services/aiScoring.service.ts"],
    debug: ["Require non-empty acceptance criteria on bounty"],
  },
  {
    code: "AI-F-001",
    domain: "AI",
    severity: "error",
    summary: "Groq provider unavailable or unconfigured.",
    messages: [
      "AI-F-001: GROQ_API_KEY is missing",
      "AI-F-001: GROQ rate limit",
      "AI-F-001: GROQ unavailable (status)",
      "AI-F-001: GROQ unavailable after retries",
    ],
    sources: ["src/services/aiScoring.service.ts", "src/inngest/jobs/aiScoring.job.ts"],
    debug: ["Set GROQ_API_KEY in .env/.env.local", "Restart API after env update", "Check Groq quota/status"],
  },
  {
    code: "AI-F-002",
    domain: "AI",
    severity: "error",
    summary: "Malformed or invalid Groq response payload.",
    messages: [
      "AI-F-002: malformed JSON response",
      "AI-F-002: malformed GROQ response",
      "AI-F-002: GROQ returned empty content",
      "AI-F-002: GROQ payload is not JSON",
    ],
    sources: ["src/services/aiScoring.service.ts", "src/inngest/jobs/aiScoring.job.ts"],
    debug: ["Inspect raw provider payload in logs", "Trigger manual review fallback", "Validate response schema fields"],
  },
  {
    code: "AI-F-003",
    domain: "AI",
    severity: "warning",
    summary: "Detected language mismatch.",
    messages: ["AI-F-003"],
    sources: ["src/services/aiScoring.service.ts"],
    debug: ["Compare detected language with bounty allowed_languages"],
  },
  {
    code: "AI-F-004",
    domain: "AI",
    severity: "warning",
    summary: "AI scoring fallback due to context/payload constraints.",
    messages: ["AI-F-004"],
    sources: ["src/inngest/jobs/aiScoring.job.ts"],
    debug: ["Reduce diff context or split scoring work"],
  },
  {
    code: "AI-F-006",
    domain: "AI",
    severity: "warning",
    summary: "Groq request timed out.",
    messages: ["AI-F-006: GROQ request timed out", "AI-F-006: GROQ scoring timed out after 30s"],
    sources: ["src/services/aiScoring.service.ts", "src/inngest/jobs/aiScoring.job.ts"],
    debug: ["Retry job", "Check provider latency", "Use smaller prompt payload"],
  },
  {
    code: "AI-F-404",
    domain: "AI",
    severity: "error",
    summary: "AI scoring context missing in DB.",
    messages: ["AI-F-404: submission context not found", "AI-F-404: scoring context missing"],
    sources: ["src/inngest/jobs/aiScoring.job.ts"],
    debug: ["Verify submission and bounty ids in event payload", "Check submission row exists"],
  },
  {
    code: "CI-V-404",
    domain: "CI",
    severity: "error",
    summary: "Submission missing for CI validation.",
    messages: ["CI-V-404: submission not found"],
    sources: ["src/services/validation.service.ts"],
    debug: ["Verify submission id from webhook/job payload"],
  },
  {
    code: "CI-V-500",
    domain: "CI",
    severity: "error",
    summary: "Unexpected CI validation failure.",
    messages: ["CI-V-500"],
    sources: ["src/jobs/ciValidation.job.ts"],
    debug: ["Inspect CI provider response and server logs"],
  },
  {
    code: "CL-001",
    domain: "COMPLIANCE",
    severity: "warning",
    summary: "Compliance provider or sanctions review issue.",
    messages: ["CL-001: provider returned status", "CL-001: User requires compliance review"],
    sources: ["src/inngest/jobs/sanctionsSync.job.ts", "src/routes/auth.ts"],
    debug: ["Check sanctions provider availability", "Review user sanctions flags"],
  },
  {
    code: "DB-001",
    domain: "DB",
    severity: "error",
    summary: "Bounty state invalid for acceptance.",
    messages: ["DB-001: Bounty cannot be accepted in current state."],
    sources: ["lib/db/queries.ts"],
    debug: ["Inspect bounty status transitions before accept"],
  },
  {
    code: "DB-002",
    domain: "DB",
    severity: "error",
    summary: "Connection pool exhausted.",
    messages: ["DB-002: Connection pool exhausted. Retry after backoff."],
    sources: ["lib/db/errors.ts"],
    debug: ["Check DB max connections", "Tune pool size and query duration"],
  },
  {
    code: "DB-003",
    domain: "DB",
    severity: "error",
    summary: "Migration rollback triggered.",
    messages: ["DB-003: Migration rollback on failure"],
    sources: ["scripts/run-migrations.ts"],
    debug: ["Inspect failed migration sql", "Run migrations step-by-step"],
  },
  {
    code: "DB-004",
    domain: "DB",
    severity: "error",
    summary: "Escrow consistency/corruption detection.",
    messages: ["DB-004: bounty action blocked (action) due to escrow corruption", "DB-004: Escrow consistency issues detected."],
    sources: ["src/routes/bounties.ts", "src/jobs/consistencyCheck.job.ts", "scripts/check-consistency.ts"],
    debug: ["Run consistency checker", "Repair escrow invariants before action"],
  },
  {
    code: "DL-404",
    domain: "DEADLINE",
    severity: "error",
    summary: "Bounty not found in deadline workflow.",
    messages: ["DL-404: bounty not found"],
    sources: ["src/inngest/jobs/deadlineRefund.job.ts"],
    debug: ["Verify bounty id in scheduled event"],
  },
  {
    code: "DL-C-001",
    domain: "DEADLINE",
    severity: "warning",
    summary: "Deadline warning event emitted.",
    messages: ["DL-C-001"],
    sources: ["src/services/payout.service.ts"],
    debug: ["Check deadline and grace period thresholds"],
  },
  {
    code: "DL-C-002",
    domain: "DEADLINE",
    severity: "warning",
    summary: "Grace-period deadline warning event emitted.",
    messages: ["DL-C-002"],
    sources: ["src/services/payout.service.ts"],
    debug: ["Check grace window job timing"],
  },
  {
    code: "DL-C-003",
    domain: "DEADLINE",
    severity: "warning",
    summary: "Bounty deadline too short.",
    messages: ["DL-C-003: Deadline is less than 24 hours"],
    sources: ["src/routes/bounties.ts"],
    debug: ["Increase deadline to >= 24h"],
  },
  {
    code: "DL-C-004",
    domain: "DEADLINE",
    severity: "warning",
    summary: "Maximum deadline extensions reached.",
    messages: ["DL-C-004: Extension limit reached"],
    sources: ["src/routes/bounties.ts"],
    debug: ["Stop extension attempts after policy limit"],
  },
  {
    code: "DL-F-002",
    domain: "DEADLINE",
    severity: "error",
    summary: "Deadline consistency/refund processing failed.",
    messages: ["DL-F-002"],
    sources: ["src/jobs/consistencyCheck.job.ts", "src/inngest/jobs/consistencyCheck.job.ts"],
    debug: ["Inspect dead letter records and consistency check logs"],
  },
  {
    code: "DS-001",
    domain: "DISPUTE",
    severity: "warning",
    summary: "Score dispute opened outside valid scoring timestamp flow.",
    messages: ["DS-001: score publication timestamp missing", "DS-001: score dispute window exceeded (72h)"],
    sources: ["src/services/dispute.service.ts"],
    debug: ["Verify score_published_at", "Check dispute open window"],
  },
  {
    code: "DS-002",
    domain: "DISPUTE",
    severity: "warning",
    summary: "Payout already confirmed beyond complaint window.",
    messages: ["DS-002: payout already confirmed beyond 24h; redirect to complaint flow"],
    sources: ["src/services/dispute.service.ts"],
    debug: ["Use complaint/escalation path instead of dispute open"],
  },
  {
    code: "DS-003",
    domain: "DISPUTE",
    severity: "error",
    summary: "Arbitrator assignment/challenge workflow invariant violated.",
    messages: ["DS-003: not enough eligible arbitrators available", "DS-003: each party can challenge only once", "DS-003: no replacement arbitrator available"],
    sources: ["src/services/dispute.service.ts", "src/routes/disputes.ts", "src/inngest/jobs/disputeResolution.job.ts"],
    debug: ["Check arbitrator pool availability", "Verify challenge counts and vote states"],
  },
  {
    code: "DS-004",
    domain: "DISPUTE",
    severity: "warning",
    summary: "Dispute escalated to senior arbitrators.",
    messages: ["DS-004", "DS-004 fallback escalation", "DS-004: no senior arbitrators configured"],
    sources: ["src/services/dispute.service.ts", "src/inngest/jobs/disputeResolution.job.ts"],
    debug: ["Verify senior arbitrator configuration", "Inspect vote split/escalation triggers"],
  },
  {
    code: "DS-005",
    domain: "DISPUTE",
    severity: "error",
    summary: "Fraud/security checks triggered during dispute resolution.",
    messages: ["DS-005: invalid MFA token", "DS-005: invalid wallet checksum", "DS-005: banned wallet review required"],
    sources: ["src/services/dispute.service.ts"],
    debug: ["Verify MFA and wallet integrity", "Check fraud and sanctions audit trail"],
  },
  {
    code: "DS-404",
    domain: "DISPUTE",
    severity: "error",
    summary: "Dispute context not found.",
    messages: ["DS-404: dispute not found"],
    sources: ["src/inngest/jobs/disputeResolution.job.ts"],
    debug: ["Verify dispute_id in event payload"],
  },
  {
    code: "GH-C-001",
    domain: "GITHUB",
    severity: "error",
    summary: "GitHub app/token not configured or not installed.",
    messages: ["GH-C-001: GitHub App installation was not found for this repository", "GH-C-001: GITHUB_TOKEN is required for repository verification"],
    sources: ["src/routes/bounties.ts", "src/routes/github.ts"],
    debug: ["Install GitHub App on repository", "Set GITHUB_TOKEN and permissions"],
  },
  {
    code: "GH-C-003",
    domain: "GITHUB",
    severity: "warning",
    summary: "No CI workflow detected in repository.",
    messages: ["GH-C-003: GitHub Actions workflow is missing for this repository", "GH-C-003: No CI/CD workflow detected"],
    sources: ["src/routes/bounties.ts", "src/routes/github.ts"],
    debug: ["Add workflow under .github/workflows", "Re-run repository validation"],
  },
  {
    code: "GH-F-003",
    domain: "GITHUB",
    severity: "warning",
    summary: "CI timeout or retrigger limit reached.",
    messages: ["GH-F-003: CI re-trigger limit reached", "GH-F-003"],
    sources: ["src/routes/submissions.ts", "src/inngest/jobs/ciValidation.job.ts"],
    debug: ["Inspect workflow runtime and retries", "Avoid repeated manual retriggers"],
  },
  {
    code: "GH-F-004",
    domain: "GITHUB",
    severity: "warning",
    summary: "CI validation reported failed checks or skipped tests warning.",
    messages: ["GH-F-004", "Warning GH-F-004: tests were skipped"],
    sources: ["src/inngest/jobs/ciValidation.job.ts", "app/disputes/[id]/page.tsx"],
    debug: ["Inspect workflow checks and skipped test count"],
  },
  {
    code: "GH-F-006",
    domain: "GITHUB",
    severity: "info",
    summary: "Exception marker for cached evidence source.",
    messages: ["EXCEPTION GH-F-006"],
    sources: ["app/disputes/[id]/page.tsx"],
    debug: ["Review source-of-truth evidence artifacts and cache freshness"],
  },
  {
    code: "GH-F-008",
    domain: "GITHUB",
    severity: "error",
    summary: "PR from unsupported fork/repository context.",
    messages: ["GH-F-008"],
    sources: ["src/inngest/jobs/ciValidation.job.ts"],
    debug: ["Verify PR base repository and installation scope"],
  },
  {
    code: "GH-F-404",
    domain: "GITHUB",
    severity: "error",
    summary: "Submission not found for CI flow.",
    messages: ["GH-F-404: submission not found"],
    sources: ["src/inngest/jobs/ciValidation.job.ts"],
    debug: ["Verify submission_id and bounty linkage"],
  },
  {
    code: "GH-W-001",
    domain: "GITHUB",
    severity: "error",
    summary: "Webhook secret missing.",
    messages: ["GH-W-001: GITHUB_WEBHOOK_SECRET is not configured"],
    sources: ["src/webhooks/github.ts"],
    debug: ["Set GITHUB_WEBHOOK_SECRET", "Restart API"],
  },
  {
    code: "GH-W-002",
    domain: "GITHUB",
    severity: "error",
    summary: "Invalid webhook signature.",
    messages: ["GH-W-002: Invalid webhook signature"],
    sources: ["src/webhooks/github.ts"],
    debug: ["Verify secret matches GitHub app settings", "Ensure raw payload verification"],
  },
  {
    code: "GH-W-003",
    domain: "GITHUB",
    severity: "info",
    summary: "Duplicate webhook delivery ignored.",
    messages: ["GH-W-003: Delivery already processed"],
    sources: ["src/webhooks/github.ts"],
    debug: ["No action needed unless dedupe logic is misfiring"],
  },
  {
    code: "GH-W-400",
    domain: "GITHUB",
    severity: "error",
    summary: "Missing required delivery headers.",
    messages: ["GH-W-400: Missing required GitHub delivery headers"],
    sources: ["src/webhooks/github.ts"],
    debug: ["Confirm GitHub sends x-github-delivery and x-github-event"],
  },
  {
    code: "GH-W-401",
    domain: "GITHUB",
    severity: "error",
    summary: "Webhook payload was not raw bytes.",
    messages: ["GH-W-401: Webhook payload must be raw bytes"],
    sources: ["src/webhooks/github.ts"],
    debug: ["Ensure express raw middleware is applied before JSON parsing"],
  },
  {
    code: "GH-W-500",
    domain: "GITHUB",
    severity: "error",
    summary: "Unknown webhook processing failure.",
    messages: ["GH-W-500: Unknown webhook processing failure"],
    sources: ["src/webhooks/github.ts"],
    debug: ["Inspect webhook processing logs and dead-letter records"],
  },
  {
    code: "RT-001",
    domain: "REALTIME",
    severity: "info",
    summary: "Reconnect hint for dispute room subscriptions.",
    messages: ["RT-001: rejoin dispute room on reconnect"],
    sources: ["src/services/dispute.service.ts"],
    debug: ["Client should rejoin room after socket reconnect"],
  },
  {
    code: "RT-002",
    domain: "REALTIME",
    severity: "info",
    summary: "Dispute realtime event dispatch marker.",
    messages: ["RT-002"],
    sources: ["src/services/dispute.service.ts", "src/jobs/disputeResolution.job.ts"],
    debug: ["Check socket emission and notification fanout"],
  },
  {
    code: "RT-003",
    domain: "REALTIME",
    severity: "warning",
    summary: "Notification delivery fallback to in-app channel.",
    messages: ["RT-003"],
    sources: ["src/services/notification.service.ts", "src/inngest/jobs/notifications.job.ts"],
    debug: ["Check email provider health", "Inspect notifications table for fallback records"],
  },
  {
    code: "SC-C-001",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Wallet balance/Algorand node health precheck failed.",
    messages: ["SC-C-001: Insufficient wallet balance to fund escrow and fees.", "SC-C-001: Algorand node health failed before payout broadcast"],
    sources: ["src/services/algorand.ts", "src/inngest/jobs/payoutRelease.job.ts"],
    debug: ["Fund wallet", "Check Algorand node connectivity and health endpoint"],
  },
  {
    code: "SC-C-002",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "On-chain operation retries exhausted.",
    messages: ["SC-C-002: Escrow creation retries exhausted", "SC-C-002: Payout retries exhausted", "SC-C-002: Unknown escrow funding failure"],
    sources: ["src/services/algorand.ts", "src/routes/bounties.ts", "src/jobs/payoutRelease.job.ts"],
    debug: ["Inspect algod transaction confirmations", "Check retry budget and network latency"],
  },
  {
    code: "SC-C-003",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Transaction confirmation/dry-run failure.",
    messages: ["SC-C-003: Unable to dry-run operation; Algorand node unavailable.", "SC-C-003: payout tx is not confirmed on-chain"],
    sources: ["src/services/algorand.ts", "src/services/dispute.service.ts", "src/services/payout.service.ts"],
    debug: ["Verify node sync status", "Retry after confirmation window"],
  },
  {
    code: "SC-C-004",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Escrow app/contract methods are not configured.",
    messages: [
      "SC-C-004: ESCROW_APP_ID missing; cannot deploy or call escrow contract.",
      "SC-C-004: Smart contract release_payout is not configured.",
    ],
    sources: ["src/services/algorand.ts"],
    debug: ["Set ESCROW_APP_ID", "Wire contract methods for environment", "Validate deploy config"],
  },
  {
    code: "SC-C-006",
    domain: "SMART-CONTRACT",
    severity: "warning",
    summary: "Wallet network mismatch.",
    messages: ["SC-C-006: Your wallet is on TestNet. Please switch to MainNet to continue."],
    sources: ["src/hooks/useWallet.ts", "app/connect/page.tsx"],
    debug: ["Switch wallet network to MainNet"],
  },
  {
    code: "SC-C-007",
    domain: "SMART-CONTRACT",
    severity: "warning",
    summary: "Bounty state blocks cancellation/accept.",
    messages: ["SC-C-007: Cannot cancel bounty while it is in progress", "SC-C-007: Active submissions exist. Cancellation blocked.", "SC-C-007: This bounty is taken"],
    sources: ["src/routes/bounties.ts"],
    debug: ["Resolve active submissions first", "Confirm bounty state transition rules"],
  },
  {
    code: "SC-C-008",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Milestone sequence/state validation failed.",
    messages: ["SC-C-008: milestone not found", "SC-C-008: milestone order mismatch against contract state"],
    sources: ["src/services/algorand.ts", "src/services/payout.service.ts", "src/inngest/jobs/milestoneRelease.job.ts"],
    debug: ["Validate milestone ids/order", "Ensure unlock before release"],
  },
  {
    code: "SC-F-001",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Invalid recipient Algorand address.",
    messages: ["SC-F-001: invalid Algorand address", "SC-F-001: invalid Algorand wallet checksum"],
    sources: ["src/inngest/jobs/payoutRelease.job.ts", "src/services/payout.service.ts"],
    debug: ["Validate wallet checksum and address format"],
  },
  {
    code: "SC-F-002",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Payout ASA opt-in/asset configuration failure.",
    messages: ["SC-F-002: payout asset id is required", "SC-F-002: freelancer asset opt-in timed out", "SC-F-002: opt-in not completed"],
    sources: ["src/inngest/jobs/payoutRelease.job.ts", "src/services/payout.service.ts"],
    debug: ["Ensure payout asset id is set", "Require freelancer ASA opt-in"],
  },
  {
    code: "SC-F-003",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Payout eligibility guard failed.",
    messages: ["SC-F-003: escrow must be locked before payout", "SC-F-003: submission must be validating before payout"],
    sources: ["src/inngest/jobs/payoutRelease.job.ts", "src/services/payout.service.ts"],
    debug: ["Check submission status, bounty status, escrow lock and threshold"],
  },
  {
    code: "SC-F-004",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Split payout or distributable amount invalid.",
    messages: ["SC-F-004: all payout shares quarantined", "SC-F-004: split sum exceeds bounty total amount", "SC-F-004: expected integer microALGO amount"],
    sources: ["src/services/payout.service.ts"],
    debug: ["Validate split weights and total", "Ensure integer microALGO math"],
  },
  {
    code: "SC-F-005",
    domain: "SMART-CONTRACT",
    severity: "warning",
    summary: "Payout amount verification mismatch/context issue.",
    messages: ["SC-F-005: Missing txId for payout amount verification."],
    sources: ["src/services/algorand.ts", "src/services/payout.service.ts", "src/inngest/jobs/payoutRelease.job.ts"],
    debug: ["Verify tx id persistence and on-chain confirmation lookup"],
  },
  {
    code: "SC-F-404",
    domain: "SMART-CONTRACT",
    severity: "error",
    summary: "Payout context missing for job execution.",
    messages: ["SC-F-404: payout context not found"],
    sources: ["src/inngest/jobs/payoutRelease.job.ts"],
    debug: ["Validate submission_id and bounty_id in event"],
  },
  {
    code: "XC-001",
    domain: "CROSS-CUTTING",
    severity: "error",
    summary: "Self-dealing blocked by policy.",
    messages: ["XC-001: Creator cannot accept own bounty", "XC-001: bounty creator cannot apply to own bounty", "XC-001: freelancer cannot equal bounty creator"],
    sources: ["src/routes/bounties.ts", "src/routes/projects.ts", "src/inngest/jobs/payoutRelease.job.ts", "src/services/payout.service.ts", "lib/db/errors.ts"],
    debug: ["Ensure actor id differs from bounty creator id"],
  },
  {
    code: "XC-002",
    domain: "CROSS-CUTTING",
    severity: "warning",
    summary: "Cross-cutting policy marker used in payout flow.",
    messages: ["XC-002"],
    sources: ["src/services/payout.service.ts"],
    debug: ["Inspect payout policy branch where XC-002 is emitted"],
  },
  {
    code: "XC-003",
    domain: "CROSS-CUTTING",
    severity: "error",
    summary: "Sanctions/compliance check failed at payout.",
    messages: ["XC-003: sanctions check failed at payout"],
    sources: ["src/services/payout.service.ts", "src/inngest/jobs/payoutRelease.job.ts"],
    debug: ["Review sanctions provider result and wallet flag history"],
  },
  {
    code: "XC-005",
    domain: "CROSS-CUTTING",
    severity: "warning",
    summary: "Cross-cutting policy/event marker used in payout workflow.",
    messages: ["XC-005"],
    sources: ["src/services/payout.service.ts"],
    debug: ["Inspect payout event payload where XC-005 is attached"],
  },
];

